namespace Dockerizer.Application.Projects;

public sealed record ProjectListItemDto(
    Guid Id,
    string Name,
    string RepositoryUrl,
    string? DefaultBranch,
    string? DefaultProjectPath,
    Guid? CurrentJobId,
    Guid? CurrentImageId,
    string? CurrentStatus,
    string? DetectedStack,
    string? GeneratedImageTag,
    string? ContainerName,
    string? ContainerStatus,
    int? ContainerPort,
    int? PublishedPort,
    bool PublicAccessEnabled,
    string? PublicHostname,
    string? RouteStatus,
    string? DeploymentUrl,
    DateTimeOffset? DeployedAtUtc,
    int JobsCount,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? UpdatedAtUtc,
    DateTimeOffset? ArchivedAtUtc);
